### ISSUE TITLE
To do: the model

### ISSUE THREAD

**Issue by robj411** [ITHIM/ITHIM-R#51]
This is a to-do list for the ITHIM-R model, which includes "global" data, parameters, and functions. Please add to it any items that are missing, and tick off items when they are complete.

- [x] Add "Uterine cancer" to GBD processing script, and update all gbd files in inst/extdata/local/CITY/gbd_CITY.csv (#21) and change "Endometrial cancer" to "Uterine cancer" in inst/extdata/global/dose_response/disease_outcomes_lookup.csv

- [x] Generalise trips data handling to allow for both single-stage trip sets and multi-stage trip sets (#50)

- [x] CHRONIC_DISEASE_SCALAR acts on Neoplasms, Ischemic heart disease, Tracheal, bronchus, and lung cancer, Breast cancer, Colon and rectum cancer, Uterine cancer. Should it act on all diseases? Could we use it to represent divergence of city from country? 
All diseases. Specific to setting.

- [x] Generate and present AP and PA health outcomes separately

- [x] Compare multiple cities side by side, which requires agreement of how to handle age (#8) and how to generate and compare across scenarios (#27)
YLL pp for the smallest age range among the settings (15 to 69)

- [ ] Update PA dose--response (#1)

- [ ] Update AP dose--response using https://github.com/ITHIM/ITHIM-R/blob/master/inst/extdata/global/dose_response/drap/dose_response_v2.csv (#2)

- [ ] Implement EPA equations (#3)

- [x] Injury module: deal with datasets where some ages/genders are missing

- [ ] Injury module: spline for ages (only worth doing if we have multiple age groups)

- [ ] age is taken from the 'population.csv' file. At present the breaks need to match the breaks in the GBD data. Need to either (a) throw an error if the breaks don't match or (b) interpolate to allow the given ages to be used.

- [x] Update AP calculation -- not dividing by volume

**Comment by robj411** [comment]
Thanks. I don't see "Uterine cancer" in the gbd files e.g. inst/extdata/local/accra/gbd_accra.csv - do you have an updated version?

**Comment by rahulatiitd** [comment]
@robj411 @usr110 @JDWoodcock 
Can we make sure that walking to PT is included for all cities, otherwise bus-related mode shift scenarios will give different results across different cities.
I accessed London Travel Demand Survey data and extracted walking duration (on both ends of the trips)  for bus and subway. See results below.
> Walking for bus
   Median    Mean 
    8.000   8.903  
> Walking for subway
   Median    Mean 
    11.00   12.51  
 This means someone making two trips by bus would accumulate at least 18 minutes and by train at least 24 minutes of walking per day. Can we use a lognormal distribution (i saw the distributions) and assign walking duration to those PT trips where these are not available?

**Comment by rahulatiitd** [comment]
> @robj411 @usr110 @JDWoodcock
> Can we make sure that walking to PT is included for all cities, otherwise bus-related mode shift scenarios will give different results across different cities.
> I accessed London Travel Demand Survey data and extracted walking duration (on both ends of the trips) for bus and subway. See results below.
> 
> > Walking for bus
> > Median    Mean
> > 8.000   8.903
> > Walking for subway
> > Median    Mean
> > 11.00   12.51
> > This means someone making two trips by bus would accumulate at least 18 minutes and by train at least 24 minutes of walking per day. Can we use a lognormal distribution (i saw the distributions) and assign walking duration to those PT trips where these are not available?

Trip level dataset to calculate distributions is here: 
for buses: code/PT_walk/walking_duration_for_buses.csv
for subway (can be used for all rail-type modes):code/PT_walk/walking_duration_for_subway.csv

**Comment by JDWoodcock** [comment]
so the 10 min estimate is not bad. What does SP look like? and do we have access/egress data for other cities
